services:
  app:
    build: .
    command: rails server -p 3000 -b '0.0.0.0'
    links:
      - postgres
    volumes:
      - .:/learning
    ports:
      - "3000:3000"

  postgres:
    image: postgres:15.1
    ports:
    - "8080:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: 'postgres'
