services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: rails s -p 3000 -b '0.0.0.0'
    links:
      - database
      - js
      - css
      - yarn
      
    env_file: .env
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true

  database:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  js:
    image: quizmo-web
    command: yarn build --watch
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    stdin_open: true
  
  css:
    image: quizmo-web
    command: yarn build:css --watch
    volumes:
      - .:/app
      - node_modules:/app/node_modules

  yarn:
    image: quizmo-web
    command: yarn install
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  db_data:
  node_modules:
